spring.application.name=OnlineSellingApplicationBackend
spring.datasource.url=jdbc:postgresql://localhost:2003/online_selling_application
spring.datasource.username=postgres
spring.datasource.password=Maamoun2003
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
