spring.application.name=OnlineSellingApplicationBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/online_selling_application
spring.datasource.username=postgres
spring.datasource.password=Mahdi1472003
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# JWT Configuration
jwt.secret=3a33a561533327fc618224ff03fe6a43162dd1921eb8c760a2427006193ca8f9
jwt.expiration=86400000
